[package]
name = "localhosh"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2"
clap= "3.2"
[dev-dependencies]
reqwest = "0.11"
tokio = { version = "1", features = ["full"] }